version: '3.8'

services:
  pacientes_service:
    build:
      context: ./services/pacientes
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./services/pacientes:/app/services/pacientes
    environment:
      - PYTHONPATH=/app

  doctores_service:
    build:
      context: ./services/doctores
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./services/doctores:/app/services/doctores

    environment:
      - PYTHONPATH=/app
